import{a as f,S as q,i}from"./assets/vendor-Boa3Yr1_.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function u(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();f.defaults.baseURL="https://pixabay.com";async function g(s,r){try{return(await f.get("/api/",{params:{key:"55214296-bcb2f99248005430efd53daac",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(o){throw console.error("Error fetching images:",o),o}}const m=document.querySelector(".gallery"),n=document.querySelector(".load-more"),a=document.querySelector(".loader"),R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const r=s.map(({webformatURL:o,largeImageURL:u,tags:e,likes:t,views:l,comments:v,downloads:S})=>`
        <a class="photo-card" href="${u}">
          <img src="${o}" alt="${e}" loading="lazy" />
          <div class="photo-info">
            <p><span>Likes:</span> ${t}</p>
            <p><span>Views:</span> ${l}</p>
            <p><span>Comments:</span> ${v}</p>
            <p><span>Downloads:</span> ${S}</p>
          </div>
        </a>
      `).join("");m.insertAdjacentHTML("beforeend",r),R.refresh()}function E(){m.innerHTML=""}function L(){a==null||a.classList.remove("is-hidden")}function b(){a==null||a.classList.add("is-hidden")}function d(){n==null||n.classList.remove("is-hidden")}function w(){n==null||n.classList.add("is-hidden")}const P=document.querySelector(".form"),O=document.querySelector(".load-more"),H=document.querySelector(".gallery");let p="",c=1,h=0;P.addEventListener("submit",async s=>{s.preventDefault();const r=s.currentTarget.elements.searchQuery.value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}p=r,c=1,E(),w();try{L();const o=await g(p,c);if(h=o.totalHits,o.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(o.hits),c*15<h?d():i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight"})}finally{b()}});O.addEventListener("click",async()=>{c+=1;try{L(),w();const s=await g(p,c);if(s.hits.length===0){i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}y(s.hits);const r=H.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),c*15<h?d():i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),d()}finally{b()}});
//# sourceMappingURL=index.js.map
