import{a as v,S as R,i as a}from"./assets/vendor-BMuTKyyJ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="https://pixabay.com/api/",q="55214296-bcb2f99248005430efd53daac",m=15;let l=0;async function h(e,o){const s=await v.get(S,{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:m}}),i=s.data.totalHits;return l=Math.ceil(i/m),s.data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),d=document.querySelector(".load-more"),B=new R(".gallery a",{});function $(e){return`<li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <ul class="stats">
        <li class="stats-item"><p class="stat-title">likes</p><p class="stat-value">${e.likes}</p></li>
        <li class="stats-item"><p class="stat-title">views</p><p class="stat-value">${e.views}</p></li>
        <li class="stats-item"><p class="stat-title">comments</p><p class="stat-value">${e.comments}</p></li>
        <li class="stats-item"><p class="stat-title">downloads</p><p class="stat-value">${e.downloads}</p></li>
      </ul>
    </li>`}function y(e){const o=e.map($).join("");f.insertAdjacentHTML("beforeend",o),B.refresh()}function A(){f.innerHTML=""}function w(){g.style.display="block"}function L(){g.style.display="none"}function b(){d.style.display="block"}function c(){d.style.display="none"}const p=document.querySelector(".form");let P="",n=1;p.addEventListener("submit",M);d.addEventListener("click",T);function M(e){e.preventDefault(),n=1;const s=new FormData(e.target).get("search-text").trim();if(s===""||s===void 0){a.show({position:"topRight",backgroundColor:"red",message:"Введіть текст для пошуку"});return}P=s,w(),A(),c(),setTimeout(async()=>{try{const t=(await h(s,n)).hits;if(t.length===0){a.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t),b()}catch(i){a.show({message:`Error: ${i}`,color:"red",position:"topRight"})}finally{if(L(),p.reset(),n>=l)return c(),a.error({position:"topRight",message:"We're sorry, there are no more posts to load"})}},200)}function T(){if(n+=1,c(),n>l)return a.error({position:"topRight",message:"We're sorry, there are no more posts to load"});w(),setTimeout(async()=>{try{const o=(await h(P,n)).hits;if(o.length===0){a.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(o),b()}catch(e){a.show({message:`Error: ${e}`,color:"red",position:"topRight"})}finally{if(x(),L(),n>=l)return c(),a.error({position:"topRight",message:"We're sorry, there are no more posts to load"});p.reset()}},200)}function x(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
